// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuJBTdv0wicKvk9P1bPr8bMN7MeyXr_Y',
    appId: '1:521563615652:ios:1c3f5dca0bb9df03099131',
    messagingSenderId: '521563615652',
    projectId: 'storemanagement-f7775',
    storageBucket: 'storemanagement-f7775.firebasestorage.app',
    iosBundleId: 'com.example.semihgiyim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXqm-0HjNXeY1b_1xQnPTTu99gS3mC2Mw',
    appId: '1:521563615652:web:764fb367b19f2fec099131',
    messagingSenderId: '521563615652',
    projectId: 'storemanagement-f7775',
    authDomain: 'storemanagement-f7775.firebaseapp.com',
    storageBucket: 'storemanagement-f7775.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqm-0HjNXeY1b_1xQnPTTu99gS3mC2Mw',
    appId: '1:521563615652:web:764fb367b19f2fec099131',
    messagingSenderId: '521563615652',
    projectId: 'storemanagement-f7775',
    authDomain: 'storemanagement-f7775.firebaseapp.com',
    storageBucket: 'storemanagement-f7775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuJBTdv0wicKvk9P1bPr8bMN7MeyXr_Y',
    appId: '1:521563615652:ios:1c3f5dca0bb9df03099131',
    messagingSenderId: '521563615652',
    projectId: 'storemanagement-f7775',
    storageBucket: 'storemanagement-f7775.firebasestorage.app',
    iosBundleId: 'com.example.semihgiyim',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBLLwSi7GzUoO1zD4G7eXr4Xkb2uLzTSk',
    appId: '1:521563615652:android:78eb028af2067149099131',
    messagingSenderId: '521563615652',
    projectId: 'storemanagement-f7775',
    storageBucket: 'storemanagement-f7775.firebasestorage.app',
  );

}